### ISSUE TITLE
How to contact author?

### ISSUE THREAD

**Issue by VictorZakharov** [Rotkaermota/Isotoxin#1]
I was reading this article:
http://habrahabr.ru/post/274417/

And have some ideas to improve UI and website:
http://isotoxin.im/

The software is cute, the only major problem I found is video quality, would be nice to fix.

Do you have a personal email? You can find mine on my website (through github profile).

**Comment by Rotkaermota** [comment]
You can write post on Isotoxin forum (http://isotoxin.im/forum) or email me at: isotoxin.dev(email)yandex.ru

btw, considering your name, you probably know russian. If so, just write me in russian.
