### ISSUE TITLE
Where do you got the smileys?

### ISSUE THREAD

**Issue by rugk** [Rotkaermota/Isotoxin#3]
From the screenshots it seem you use the Apple ones. But are they license free?

**Comment by Rotkaermota** [comment]
Apple emoji's used in many messengers, Telegram, for example. You think telegram devs buy rights from Apple to use their emoji? I don't know. May be. I just independent developer, who doesn't make money from his project. I have no either time or desire to explore copyrights wisdom. If apple decides that I have no right to use their emoji, I just delete them from my messenger.
If you copyright warrior, just show me text with direct prohibition to use apple emoji by free opensource programs from apple.

**Comment by rugk** [comment]
> If you are copyright warrior

No, I am not. 😱

I was just curios... 

So I've looked a bit around and found a [Stackoverflow question](https://stackoverflow.com/questions/10834811/emoji-copyright) linking to a [GitHub repo](https://github.com/github/gemoji) where it is also stated that the emoticons [are licensed by Apple](https://github.com/github/gemoji/blob/master/LICENSE#L14).
So I would also assume that Apple can disallow you to use these icons.

**Comment by Rotkaermota** [comment]
So
http://stackoverflow.com/questions/22337295/license-of-apple-color-emoji-ttf/22949517#22949517
> So the answer is that there is no license for 'Apple Color Emoji.ttf' available.

and

> The missing license means that using the pictures could be prosecuted by Apple. It seems they didn't do this yet, though.

So, I will continue to include Apple emoji into Isotoxin's distribution archive until Apple prohibit do it. It just a emoticons pack, one of four, included in archive. It is not so important to provide Aplle emoji pack with Isotoxin. I can easy remove it.

**Comment by GrayHatter** [comment]
FWIW, if they delay too much longer, it'll become unenforceable. If you know your icons are being used, and don't do anything to stop others. You'll lose the ability to stop anyone. Apple's lawyers know this, so the clock is ticking.
